// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOPL/KgT3D/zfyHba7QEHv0vTJ6NPQbPtvmiDYiyOLW4kUkuO7MsV/u4HkpIt",
	"W7Ts5pJsDpt3sUjODOfxN8P84KkuSq1QkeXjH9ymGRbg/zydoyL3R2l0iYYk+s+pQSAUp35ppk0BxMdc",
	"AOGAZIE84XRdIh9zS0aqOV8l7ohARRLyzyZ3xzo7pNiiVlVSxAhZAqq8FKiqgo+/cqVpkGqlMCV0R5Yg",
	"Sar5YKbNYMPW8oSjMdrwhM+BMnQEB1JJtziQaoGKtLnmCa/KAemBuw1PuNWVSXEw1wr55V5xJmqmo5eq",
	"SvGzmlqgsVKrCLlVwg3+WUmDwt3b66dWx5Ygu9pOWgZri7ThtbmZnv6BKTk5XnpldWxfoLUwR/enQJsa",
	"WZKXNuxnzXJyQPhm36XjtLgtLxNA4HZLwsLT+D+DMz7mv4w2Lj6q/Xvk2b5wJ1ZrUmAMXHeEbavPs4jq",
	"a02uc5MrvI56xwLyCg8b2h1vNsc4T9TMRLg6SS1pE36tVbK9aWYQz6CEVNL16+ctWaQinKPxutEE+cFN",
	"/suhq/jVLsVkV47YNbdNlPBMWzrXSzQXBBRuA0JI546Qn2/dcp+4LeqOmj1Hc5ZXltBsqWzv8bUsCmmp",
	"zVWfpsXCLiWlWdQTFBQYXWjU2iQ7S6AEGBf6Qrpt0ypkvTX5hFfKVmWpjVuI5axFDmoijjaWl+0YgwSr",
	"Bv3ZHld641QdW9/lv9m8S7xrr64/tKyStIMhHkJN/u/YTTbR1ZdLQgg63aaoavfp2//lLGxzJw5nqi/v",
	"bUc5DaNAIKnFjN3tvZwbcFExsbbqTQZgLVpb1Nm4W8N1tbXSsmsOU8wPe1TYlrQZNWSPcbALX4wjcjcw",
	"pU+JAcuskpvUlSOxiWx7Ub+7NBv7Yl+rc4OFtFs5bKp1jqBuBC5iAMJz348QWjLELBQscuYPd+2y92bW",
	"ZufVNJfp22hl3JFzbwIK3N9JS0cX/dqF9jrXZ3/3j/7Wexzt+x16w66FWrB0zTuqiTUq3gZl4TuTlgEz",
	"SJVRzOMINtOGpZDnllEGxIRW/0/NDu3QMQvE7ZAnxyLAU5ZVBaiBQRAwzZG1lpmeMcqQBZgafknLHF2f",
	"m4YxDRoEG5DwLqMC0kwq3MtqmV3vMHA6kMrL8I2/AplXBr/xWp4hm9QCBe1Iy7AoydFA438qzaQKJnfE",
	"YAEyd4yH7JR98mKyNAcjZxItA8Xe/PbbeXPZVAtk08ppGR0lYnqBxkiBTNKwv8mJmrPW5UZ57KNCpmdj",
	"9o1fVGmK1n7jTJv2TYfsvXZXUTM9ZhlRacej0VzS8Oqfdii188uiUpKuR6lWAVdoY0cCF5iPrJwPwKSZ",
	"JEypMjiCUrqey3mn1MoOC/GLLTEdgBKDdUvSjeqO3zZ1sFt1xVENUCwWvrz/hKFte24QroReqi79TFrS",
	"cwNFHDf/JPwrpPqyg+Vbuy1heQTcWROpT/T0Gh4M9SCsV9qEqu9c9Nh9v0vKfgejpJrb/jMfNPWT37nZ",
	"RtmN6FE5Dwq1T4K4F0QATlpWZ01D1A+4ui608oj76qwBQTc8H/qnGxwuGhjXtlEfnV3c56BGW20hbd2E",
	"jP5vm63y1to2A8WNNXooio4KoePjJ9bd8C6rZOOlzfXWntN2QW+GbVXuMXDMd2IhUxq0cq5QDKowo9sO",
	"HvxXKQ3a70CR4Y9bC6XRQU8PL1yJ+vzpHSN9hb6+H4e1a97b9M8NDoJsnqQj76yYaxBSzT0r3wANUC2Y",
	"kDZ1FfaayQLmODwIhB3LrkJWHsOFwV4uU1QWN6CWn5aQZsieDk94LTNvqupyuRyCXx5qMx/VZ+3o3eTs",
	"5YeLl4Onw5NhRkXufUiSc69Nk8bOc1AKDTs9n7QmdGNeKYEzqVD4CCxRQSn5mP86PBk+cX4AlHkzudo8",
	"WjwZ4aIZ6JbaRkxWgrUsbGIzowtWSUaaXcHsCrjnUIe9cPqvbPYyEAyqQ0vPtfDQ1uGFuv+Cssxl6o+N",
	"/qihWwjCo4ZxQecby5Cp0H+wpVZ1G/T05MmtMW2aAcd1Wzkf3zotPzs5ub0L+nFqhNVzEOxT0Gjg+eTu",
	"eX5WUFGmjfx3cKdnJ7/ePdNX2kylEOhz7z/uQ7UThy0V5OwCzQINazYmnMDl6K+8knUI8Ev3uYmdUCxq",
	"AJ4jRZqd8J0BS3WeY9o0Hs3J3QB64bdfrFd3fPr2lFF3gj0+/Rf41/1aGztmDlbxjw1zjOTCXFraa7p3",
	"0tLGcCUYKDBMOL/u0vGtk87ZMgNC53GuMAmcQZW77rrUhpjNdJULNkUGQqBwOdftMmirnPwgj4/5nxX6",
	"pr8uNlKleSXwe03KdQhrXe3OhVaXd+ldm4nLQ/KwuKnjdS9MuhjU9u6YOwyzLprFuyh2W1OzB1Pzgjzi",
	"b1X4Hkxi6haf0Q8pVkdVoD2O3C45hxLX5MV6QNfslwEkUtZKQ4Lvumo7Ex2YiN5DYnqEcn8BlHt28uzu",
	"OX7Q9EpX6v6CdsPwJ3DEHCkEUYmpnEkU+2LzNdJjYD4G5mNg3hXML6tIeIaHzXXFDGOP9Rsbm8m8G6nh",
	"QfChBetdYdKt58+jkOk9WPxUsY9fTsMw7zFlPKaMO5gDHcLho+B84x/9dX/jppGCP6kXelOIFPeQQpLO",
	"LNj/Mwa7uHjDwj8bxoYQ1mZv/WJn9nBDIKFTQhpYMhieYSMXmEoFXoZdTo9JYpMk/p4hGyztan2GILox",
	"6b4eCMo3COLhROWe4OkBzcc441EV5nBFOOgONzVfb8JtHiKjSff1btJlCwns86d3+7utF/WbYdjUa/Jw",
	"gHlL/W91XNvPuLEM4h9l1w+oj3nznqcIbdfPEHLK9vp4WGZphulVLH3l3iePSxstCWqul15i60M0xEB4",
	"yB7x1eXqPwEAAP//3D077hc0AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
