// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX2/bOBL/KgT3gHuR7bTbAw5+S9N2a3TbBs02+9AGi7E4triRSC05spEr/N0PJCVb",
	"tmjZzSbZAM1bbJLz9zczP9L5xlNdlFqhIsvH37hNMyzA/3k6R0Xuj9LoEg1J9F+nBoFQnPqlmTYFEB9z",
	"AYQDkgXyhNNNiXzMLRmp5nyVuCMCFUnIP5vcHevskGJLWlVJERNkCajyVqCqCj7+wpWmQaqVwpTQHVmC",
	"JKnmg5k2g41ayxOOxmjDEz4HytAJHEgl3eJAqgUq0uaGJ7wqB6QHzhuecKsrk+JgrhXyq73mTNRMR52q",
	"SvG9kVqgsVKriLhVwg3+VUmDwvnt41OHY8uQ3WgnrYS1Tdro2nimp39iSs6O1z5YndwXaC3M0f0p0KZG",
	"luStDftZs5wcML7Zd+U0Le4KZQII3G5JWHgZ/zI442P+02gD8VGN75FX+8qdWK1FgTFw0zG2HT6vIhqv",
	"tbiOJ9d4E0XHAvIKDyfaHW82xzRP1MxEtDpLLWkTPq1Dsr1pZhDPoIRU0s0vL1u2SEU4R+Njownyg5v8",
	"N4dc8atdicmuHTE3t1OU8ExbOtdLNBcEFLwBIaSDI+TnW17uM7cl3Umz52jO8soSmq2Q7T2+tkUhLbW5",
	"7ou0WNilpDSLIkFBgdGFJqxNs7MESoBxpS+k2zatQtdbi094pWxVltq4hVjPWuSgJuLoZHnbjklIyGqI",
	"n+2B0lsX6tj6rv7N5l3h3Xx18dDKStIuhngJNf2/kzfZVFdfLwkl6GKboqrh07f/8ixscycOd6rL97YT",
	"nEZREJDUZsZ8ey/nBlxVTKytepsBWIvWFnU37s5wXW2ttPKawxTzw4gK25K2okbsMQC78MM4YndDU/qC",
	"GLjMKrnNXDmSm8g2ivrh0mzsq32tzg0W0m71sKnWOYK6FbmIEQivfT9DaNkQy1DIyJk/3M3LXs+szc6r",
	"aS7Td9HJuGPn3gYUtP8qLR099GsI7QXXZ+/7R+/1HqD9cY9o2M1Qi5audUcjsWbF26QsfM+kZcAMUmUU",
	"8zyCzbRhKeS5ZZQBMaHVv6nZoR07ZkG4HfLkWAZ4yrKqADUwCAKmObLWMtMzRhmyQFPDJ2mZk+t70zAW",
	"QYNgAxPeVVRAmkmFe1Uts5sdBS4GUnkbvvI3IPPK4Fde2zNkk9qgEB1pGRYlORlo/EelmVQh5U4YLEDm",
	"TvGQnbJP3kyW5mDkTKJloNjb3347b5xNtUA2rVyU0UkiphdojBTIJA37LznRdNax3ASPfVTI9GzMvvKL",
	"Kk3R2q+cadP2dMjea+eKmukxy4hKOx6N5pKG1/+1Q6kdLotKSboZpVoFXqGNHQlcYD6ycj4Ak2aSMKXK",
	"4AhK6e5cDp1SKzssxE+2xHQASgzWV5JuVXdw28zB7tQVR12AYrVw+f4ThmvbS4NwLfRSdeVn0pKeGyji",
	"vPk76V8h1eUOl2/ttoTlEXRnLaQ+0XPX8GSoh2G90SZMfQfRY/f9Lin7HYySam77z3zQ1C9+x7NNsBvT",
	"o3YeNGqfBXEURAhOWlZnzYWon3B1IbTyjPv6rCFBtzwf7k+3OFw0NK6doz45u7zPUY122ELbuo0Y/Xcv",
	"W+WdXdsMFLeO6KEqOqqEjq+f2O2Gd1UlG5Q27q2R04agT8N2KPckOIadbsmsPGUJ71i5TFFZ3HA4flpC",
	"miF7PjxxBNHkfMybIbJcLofgl4fazEf1WTv6dXL2+sPF68Hz4ckwoyL3IZPkorm5k7DzHJRCw07PJ60H",
	"qTGvlMCZVCg84EpUUEo+5j8PT4bPnNtAmY+yG0WjxbMRLpr3y1IHPrg9OkuwloVNbGZ0wSrJSLNrmF0D",
	"9xpqlAs+5ueVzV4HgSFpaOmlFp7JufFYXzegLHOZ+mOjP2umEjB31NtTiPkGE2Qq9F/YUqua9T8/eXZn",
	"Shvu67RuB+fjOxflFycnd+egfz2MqHoJgn0KEQ06n92/zs8KKsq0kf8LcHpx8vP9K32jzVQKgb7V/Och",
	"QjtxVEpBzi7QLNCwZmPCCVxL+sIrWZcAv3JfN7UTemPNN3OkCLcP3zNgqc5zTBue3ZzcLaBXfvvFenUH",
	"03cXjPri04PpfwBfD5tt7KQ5ZMW/rc8x0gtzaWlv6tx1epO4EgwUGB70vuzK8TcFnbNlBoQOce5WInAG",
	"Ve4uk6U2xGymq1ywKTIQAoXruW6XQVvl5N+t+Jj/VaG/49bDRqo0rwT+UYtyhHgdq91nkNXVfaJr88Dw",
	"mBAWT3V87oWHHQZ1vjvpDm83F83ifQy7rUeiRzPzgj3ihxp8j6YxdYfP6JsUq6Mm0B4gt0fOocY1ebV+",
	"j2r2y0ASKWu1IcF3odruRAceAB+gMT1RuX+Ayr04eXH/Gj9oeqMr9XBFu1H4HTxijhSKqMRUziSKfbX5",
	"C9JTYT4V5lNh3hfNL6tIeYbf8dYTMzx7rH9SYjOZdys1/P712Ir1vjjp1q99RzHTB8j4qWIfL0+ZLGCO",
	"Ty3jqWXcwzvQIR4+CuAbf+uf+xuYRgb+pF7obSFSPEALSTpvwf5/D9jFxVsW/rcu9ghhbfbOL3beHm5J",
	"JHRKSANLBsOvjhEHplKBt2FX01OT2DSJH7NkQ6bdrM8QRLcm3bcHivItgng8VbmneHpI8zFgPGrCHJ4I",
	"B+Fw2/S5hpsh5JTt7a5hmaUZptexHOY+CcfFrmVBrfXKo896O0Puw695I766Wv0/AAD//7SqU0ALMAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
