// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYX2/bNhD/KgK3R9ly0u7Fb0nWrsbWLmjQ9qEIhot4tthIpEaeYmSFvvtAUrJli5YV",
	"rxm2YW+JeLw/v7v73dFfWaqKUkmUZNj8KzNphgW4Py9WKMn+UWpVoiaB7nOqEQj5hTtaKl0AsTnjQDgh",
	"USCLGT2WyObMkBZyxerYXuEoSUD+Qef2Wk9C8B1tVSV4SJEhoMp5gbIq2Pwzk4omqZISU0J7ZQ2ChFxN",
	"lkpPtmYNixlqrTSL2QooQ6twIqSwhxMhH1CS0o8sZlU5ITWx0bCYGVXpFCcrJZHdHnRnIZcqGFRV8qci",
	"9YDaCCUD6uqYafy9Ehq5jdvh08Cx48g+2nEnYV2Xtra2kam7L5iS9cPl/sZp/eCuBOvgSFI9fL89ObdP",
	"xXk0aOPwatV1Awhh9MoVVA+XAo2BlQOMo0m1KMk55+Wj9jg+4msrd1vHbCGXGvqWOBAYUtr/JwgL0xda",
	"asQrKCEV9PjTZQcjIQlXqG0kpAjyo0LuyzGI3WlfY7zvRwjQ5gNoDY/2/0wZulZr1LYQfTTAubBwQn69",
	"E+UhdzvarTZzjfoqrwyh3oHs4PWNLxJprfT9ENL8wawFpVmwRiUUGDxoYW0JzRBIDtq2CBdW7K7yzLZR",
	"H7NKmqoslbYHIV56yEEu+OhkOd/GJMRn1eNnBkrpjYU6dL5vfyu8r7yfr349dLISd5shFMpiw/G9vIm2",
	"u77XuGRz9l2yHYlJMw8T34IW2xRlUz5D8h+vvJi94YtlUPqt6YHTGvIK4sbNUGxvxUqD7YqFMdUgGYAx",
	"aEzRzPX+nFbVzkknrzncYX68orxY3DXUqh1TYDeOcAN+t6vIEIh+X6njUzaUkTNKdKtouFxawaHeV/Ja",
	"YyHMDofdKZUjyJMWiNCS4Kwf3gI6PoQy5DMyvAm47CyeD8H9qDrrWms65Hrbgv2G56P2q6DOt+/RbwWX",
	"GuGeq7Xs68+EIbXSUIRH9hMnTyHkR8grDEsbwnIE026UNDc8X4Z70vLwALm/VtoTDtzlOFbuk6DsE2gp",
	"5MoM33mnaFj9XmRbsFvXg34edeqQB+EqCHBrWlZX7S42zPX9EqrdsL+/avn3xPt+dTvhctFOkG6OhvTs",
	"jxzLcl3Y3iMYJU9Ro/7qnld+s41RQ3Eyose6aFQLje+f0GLF+qbibZW24W0qp1uCLg27UB5IcKh2+i1T",
	"O+b3z7dcpCiNC9sPRnZRQpphdD6d2dlkH5MsIyrNPEnW6/UU3PFU6VXS3DXJL4urV+9uXk3Op7NpRkXu",
	"IBNk0dyuQ9F1DlKiji6uF9EkcrMiQslLJWT3ATxnleS4FBK5q8ASJZSCzdmL6Wx6ZnEAyhzsCZQieThL",
	"nCqTfBW8Trbv1rKi/qvPz9rIS0VqGVGG3hXmTDX1z9mc+fnaeXo70xoK9Pv2533dix93tAn7zfraTv25",
	"3wC2lUG6wrj5jWfEuK5v/WU0dKm4G9mpktTsYlCWuUid+8kX49/fW9VHN7WdnaKufQmbUslmHTqfzfpo",
	"/vqzzdD57OzQ0Ut/65u46R/4zrNdU5fAo/ceF2/z7PltfpBQUaa0+MNX6cvZi+c3+lrpO8E5Sm/x5fNb",
	"fKcoWqpKuhh/+DuSubBLooQ8ukH9gDpqBWNGYMn2c/P6uLWfWgLwjP8UBjCuVTe7q2UCiLyaA0TgV+9F",
	"Z9s9RgYNu2y0/msIIfDKqHdnmnX0AEN8Qw9C9fE/r/xHeOX1P4xWmjb1vJIh5OR+OlxhgEP8cZRmmN73",
	"6OKNvzt2fnZcaKzeOv+Nc9RTi9/CElbf1n8GAAD//3Opl1IiGgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
