// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTXPbNhP+Kxy875ESZSe96Ga7caJpPjx2nRw8mg5ErETEJMACS2lUD/97BwApUSJE",
	"0WqcST9OtonF7uLZr2f9RGKZ5VKAQE3GT0THCWTU/nqxAIHml1zJHBRysJ9jBRSBXdijuVQZRTImjCIM",
	"kGdAQoLrHMiYaFRcLEgZmisMBHKa3qvUXGtJcLajrSg48ynSSLGwXoAoMjJ+IELiIJZCQIxgrqwoRy4W",
	"g7lUg61ZTUICSklFQrKgmIBROOCCm8MBF0sQKNWahKTIBygH5jUkJFoWKobBQgog04PuTMRceh9V5Oy5",
	"SC1BaS6FR10ZEgW/F1wBM++2+FRw7Diyj3bYCFjTpa2t7cvk7CvEaPywsb+zWu/tFW8eHAmqg++3Z8f2",
	"uTj3Bq0fXrW65gN8GL2xCdXCJQOt6cICxkDHiudonXPyQX0cHvG1lpuWIZmIuaJtS4wi1SiV+4sjZLot",
	"NFcAVzSnMcf128sGRlwgLECZl6BEmh4Vsl+OQWxP2xrDfT98gFYfqFJ0bf5OpMYbuQJlEtG9hjLGDZw0",
	"vdl55SF3G9qNNn0D6iotNILagezg9Y0vAnAl1WMX0mypVxzjxJujgmbgPahhrRuaRioYVaZEGDdis8J1",
	"to36kBRCF3kulTnw9aVlSsWE9Q6W9a1PQFxUHX66I5XeGah95/v2t8L7ytvxaudDIyphsxh8T5lsenwr",
	"bryurv8rmJMx+V+0HYlRNQ8jV4IG2xhElT5d8p+vnJi54ZKlU/qDboFTG3IKwspN39s+8IWipiomWhed",
	"zYBqDVpn1Vxvz2lZ7Jw04prSGaTHM8qJhU1Dtdo+CXZnG67H75qKdIHo+EoZnsJQes4o3syi7nSpBbtq",
	"X4obBRnXOz1sJmUKVJxEIHwkwVo/zAIaPvgi5CLSzQRsdCYvh+D+qxp0rTbtc70uwXbBs178yqvzwy04",
	"VnCpgD4yuRJt/QnXKBeKZv6R/czJk3HxmaYF+KU1Qt6j026UVDdcv/TXpOnDHc39WirXcOgshb5yXzgm",
	"X6gSXCx0952PErvV771sC3btutfPo04d8sCfBZ7eGufFVc3Funt9O4VKO+wfr+r+e+J9R91OuJzVE6QZ",
	"oy49+yPHdLkmbLdAtRSnqJF/lefl34wxKpqdjOixKupVQv3rx0esSNtUuM3S+nmbzGmmoA3DLpQHAuzL",
	"nXbJlLbzu/Ut5TEIbZ/tBiO5yGmcQHA+HJnZZJZJkiDmehxFq9VqSO3xUKpFVN3V0fvJ1ZuPd28G58PR",
	"MMEstZBxNGhu6VBwk1IhQAUXN5NgENhZEYBgueSiuQCPSSEYzLkAZjMwB0FzTsbk1XA0PDM4UEws7BHN",
	"ebQ8i6wqHT1xVkbbvTUvsL31uVkbOKlAzgNMwLlCrKkq/xkZEzdfG6u3Na1oBo5vP+zrnvy8o42bb8bX",
	"euqPHQPYZgaqAsLqfzw9xnU5dZdB46VkdmTHUmDFxWiepzy27kdftdu/t6qPMrUdTlGWLoV1LkVFh85H",
	"ozaan34xETofnR06eu1ufRM33YJvPds1dUlZcOtwcTbPXt7mvaAFJlLxP1yWvh69enmj11LNOGMgnMXX",
	"L2/xo8RgLgth3/jT9wjmxJBEQdPgDtQSVFALhgSpabYP1fYxNZ/qBsAzuoBotkb5CCJ6sj/K6MlUXWk8",
	"WYCnFbwFtPX66fNFYBUES06D+9v3rU7wFnBiBC7XvxrNx/rAvQYVYCXp6QL10eFG0CLDrVZj/a12CY+J",
	"6qS/ham/3A/EWsYIONCowLFqTwubcUHtTrBvqRXxC7ENwb+sZ3yfCr7+QQpYQ1wojmsyfphuy9nFfaec",
	"HYF7zkDXtpI3q6gZ7DRwag7MdbdJTxrL67HZXpGFjda/zXz3/NOg3KWoxtHyWR3gFA982fIfTfiH0ITr",
	"H4wlVGXq+koCNMXkIBNwx0GcQPzYahfv3N2+dLjhQmV1WrrmZxx1rcUtVREpp+WfAQAA///idiNL8R0A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
